#!/usr/bin/env python3

import sys
from collections import Counter

data = [x.strip() for x in sys.stdin.readlines()]

def filter(data, common_index, tie_breaker):
    for y in range(len(data[0])):
        counts = Counter([x[y] for x in data])
        freq = (counts['0'], counts['1'])
        selected = counts.most_common()[common_index][0]

        if freq[0] == freq[1]:
            selected = tie_breaker

        data = list([x for x in data if x[y] == selected])

        if len(data) == 1:
            return int(data[0], 2)

o2rating = filter(data, 0, '1')
print(o2rating)
co2rating = filter(data, 1, '0')
print(co2rating)
print(o2rating * co2rating)
sys.exit(0)
