#!/usr/bin/env python3

import sys
from collections import Counter

data = [x.strip() for x in sys.stdin.readlines()]

gamma = [Counter([x[y] for x in data]).most_common()[0][0] for y in range(0, len(data[0]))]
gamma = ''.join(gamma)
gamma = int(gamma, 2)
epsilon = (~gamma) & 0b111111111111

print(gamma * epsilon)
