#!/usr/bin/env python3

import sys

data = [int(x.strip()) for x in sys.stdin.readlines()]
data = [sum(x) for x in zip(data, data[1:], data[2:])]
print(sum([1 for x in zip(data, data[1:]) if x[0] < x[1]]))
