#!/usr/bin/env python3

import hashlib
import sys

secret = sys.argv[1]

i = 0
while True:
  i += 1
  if hashlib.md5(('%s%s' % (secret, i)).encode('ascii')).hexdigest().startswith('00000'):
    print(i)
    break
