#!/usr/bin/env python3

import sys

data = [(x[0], int(x[1])) for x in [x.split() for x in sys.stdin.readlines()]]

print(data)
horizontal = sum([x[1] for x in data if x[0] == 'forward'])
print(horizontal)
depth = sum([x[1] for x in data if x[0] == 'down']) - sum([x[1] for x in data if x[0] == 'up'])
print(depth)
print(depth * horizontal)
